//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportOMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class OMS_LOAD_PRODUCTO
    {
        public long ID { get; set; }
        public string NOMBRE { get; set; }
        public string ESPECTACULO { get; set; }
        public Nullable<System.DateTime> FECHA_ESPECTACULO { get; set; }
        public string CIUDAD_ESPECTACULO { get; set; }
        public Nullable<System.DateTime> FECHA_LLEGADA { get; set; }
        public Nullable<System.DateTime> FECHA_SALIDA { get; set; }
        public Nullable<int> TIPO_TRANSPORTE { get; set; }
        public Nullable<int> TIPO_ESPECTACULO { get; set; }
        public Nullable<int> TIPO_HOSPEDAJE { get; set; }
        public string RUTA_IMAGEN { get; set; }
        public Nullable<short> ROUTE { get; set; }
    
        public virtual OMS_LOAD_CIUDAD OMS_LOAD_CIUDAD { get; set; }
        public virtual OMS_LOAD_TARIFA_ESPECTACULO OMS_LOAD_TARIFA_ESPECTACULO { get; set; }
        public virtual OMS_LOAD_TARIFA_HOSPEDAJE OMS_LOAD_TARIFA_HOSPEDAJE { get; set; }
        public virtual OMS_LOAD_TARIFA_TRANSPORTE OMS_LOAD_TARIFA_TRANSPORTE { get; set; }
    }
}
