//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportOMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class OMS_MENU
    {
        public OMS_MENU()
        {
            this.OMS_ROL = new HashSet<OMS_ROL>();
        }
    
        public int IdMenu { get; set; }
        public string NombreMenu { get; set; }
    
        public virtual ICollection<OMS_ROL> OMS_ROL { get; set; }
    }
}
