//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportOMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class OMS_CIUDAD
    {
        public OMS_CIUDAD()
        {
            this.OMS_PRODUCTO = new HashSet<OMS_PRODUCTO>();
        }
    
        public string ID_CIUDAD { get; set; }
        public string PAIS { get; set; }
        public Nullable<int> TIPO_CIUDAD { get; set; }
        public string NOMBRE_CIUDAD { get; set; }
    
        public virtual OMS_TARIFA_CIUDAD OMS_TARIFA_CIUDAD { get; set; }
        public virtual ICollection<OMS_PRODUCTO> OMS_PRODUCTO { get; set; }
    }
}
