//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportOMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class OMS_TARIFA_TRANSPORTE
    {
        public OMS_TARIFA_TRANSPORTE()
        {
            this.OMS_PRODUCTO = new HashSet<OMS_PRODUCTO>();
        }
    
        public int ID { get; set; }
        public string NOMBRE_TARIFA_TRANS { get; set; }
        public Nullable<decimal> PRECIO_TRANSPORTE { get; set; }
    
        public virtual ICollection<OMS_PRODUCTO> OMS_PRODUCTO { get; set; }
    }
}
