//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportOMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class OMS_CAMPANAS
    {
        public OMS_CAMPANAS()
        {
            this.OMS_CAMPANA_PRODUCTO = new HashSet<OMS_CAMPANA_PRODUCTO>();
        }
    
        public long IdCampana { get; set; }
        public string RutaImagen { get; set; }
        public System.DateTime FechaInicial { get; set; }
        public System.DateTime FechaFin { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<OMS_CAMPANA_PRODUCTO> OMS_CAMPANA_PRODUCTO { get; set; }
    }
}
