//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportOMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class OMS_CAMPANA_PRODUCTO
    {
        public long Id_Campana_Producto { get; set; }
        public long IdCampana { get; set; }
        public long IdProducto { get; set; }
    
        public virtual OMS_CAMPANAS OMS_CAMPANAS { get; set; }
        public virtual OMS_PRODUCTO OMS_PRODUCTO { get; set; }
    }
}
