//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportOMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class OMS_TARIFA_CIUDAD
    {
        public OMS_TARIFA_CIUDAD()
        {
            this.OMS_CIUDAD = new HashSet<OMS_CIUDAD>();
        }
    
        public int ID { get; set; }
        public string NOMBRE_TARIFA { get; set; }
        public Nullable<decimal> PRECIO_CIUDAD { get; set; }
    
        public virtual ICollection<OMS_CIUDAD> OMS_CIUDAD { get; set; }
    }
}
