//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportOMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class OMS_PRODUCTO
    {
        public OMS_PRODUCTO()
        {
            this.OMS_CAMPANA_PRODUCTO = new HashSet<OMS_CAMPANA_PRODUCTO>();
        }
    
        public long ID { get; set; }
        public string NOMBRE { get; set; }
        public string ESPECTACULO { get; set; }
        public Nullable<System.DateTime> FECHA_ESPECTACULO { get; set; }
        public string CIUDAD_ESPECTACULO { get; set; }
        public Nullable<System.DateTime> FECHA_LLEGADA { get; set; }
        public Nullable<System.DateTime> FECHA_SALIDA { get; set; }
        public Nullable<int> TIPO_TRANSPORTE { get; set; }
        public Nullable<int> TIPO_ESPECTACULO { get; set; }
        public Nullable<int> TIPO_HOSPEDAJE { get; set; }
        public string RUTA_IMAGEN { get; set; }
        public Nullable<short> ROUTE { get; set; }
    
        public virtual ICollection<OMS_CAMPANA_PRODUCTO> OMS_CAMPANA_PRODUCTO { get; set; }
        public virtual OMS_CIUDAD OMS_CIUDAD { get; set; }
        public virtual OMS_TARIFA_ESPECTACULO OMS_TARIFA_ESPECTACULO { get; set; }
        public virtual OMS_TARIFA_HOSPEDAJE OMS_TARIFA_HOSPEDAJE { get; set; }
        public virtual OMS_TARIFA_TRANSPORTE OMS_TARIFA_TRANSPORTE { get; set; }
    }
}
