using System;
using System.Collections.Generic;
using System.Text;

namespace TouresB2CTest
{
	public static class BaseTest
	{
		public static string Token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImp0aSI6ImMyYjk5NWY2LWE4N2MtNGUxYS1iNWRiLWNhNWQwNjlkMzM3ZSIsIm5iZiI6MTUzOTczMjI0NiwiZXhwIjoxNTM5ODE4NjQ2LCJpc3MiOiJ0b3VyZXMudG9rZW4uaXNzdWVyIiwiYXVkIjoidG91cmVzLnRva2VuLmF1ZGllbmNlIn0._FAMnUU3-N5DKNnTCtqacWkeQUJ8Z45OGpV7XChPt3w";
	}
}
